#!/bin/sh
#
# Copyright (C) 2011 <fwhacking|gmail:com>
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

JAVA=$(which java)

if [ -z $JAVA ]; then
	echo "Please install 'java'"
	exit 1
fi

if [ $# -lt 1 ]; then
	echo "Usage: $0 file"
	exit 1
fi

$JAVA ByteEntropy -c -r 512 -w 200 -o $(basename $1).ent -f $1
